version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - app
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - app
    volumes:
      - .:/app/
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - app
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app:

volumes:
  pgdata: